version: '3.7'
services:
  db:
    image: mysql:8.0
    ports:
      - '3000:3306'
    volumes:
      - ./data:/var/lib/mysql
      - ./src/test/resources:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app_db
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass